"""CGEL PreToolUse guard for Bash — blocks destructive commands, and
blocks AI attribution in authored commits/PRs.

Safety gate -> fails CLOSED: unreadable payload blocks the call (exit 2).
This is a guardrail on the raw command string, not a sandbox; indirect
mutations (scripts, interpreters) are out of reach on Profile A hosts.

A destructive command runs if the transcript carries the user's recorded
AskUserQuestion approval quoting the exact command (see approvals.py) —
the approval both unblocks it and suppresses the permission prompt, so
the user answers one readable question instead of retyping commands.
The attribution rules have NO approval path: they are policy, not risk.

Bypass, per command, typed by the USER: prefix `CGEL_GIT=allow `.
Kill switches: env CGEL_GIT_GUARD=off, or .cgel/config.json
{"git_guard": "off"}; attribution only: {"ai_attribution_guard": "off"}.
"""

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import approvals
import cgel_common as C

RULES = [
    (
        "force-push",
        re.compile(
            r"git\s+push\s+(?:[^\n|;&]*\s)?(?:--force\b(?!-with-lease)|-f\b)"
        ),
        "git push --force rewrites remote history (--force-with-lease is allowed)",
    ),
    (
        "remote-branch-delete",
        re.compile(r"git\s+push\s+[^\n|;&]*(--delete\b|\s:\S+)"),
        "deleting a remote branch",
    ),
    (
        "reset-hard",
        re.compile(r"git\s+reset\s+[^\n|;&]*--hard\b"),
        "git reset --hard discards local work",
    ),
    (
        "clean-force",
        re.compile(r"git\s+clean\s+[^\n|;&]*-[A-Za-z]*f"),
        "git clean -f deletes untracked files",
    ),
    (
        "checkout-dot",
        re.compile(r"git\s+checkout\s+(--\s+)?\.(\s|$|;|\|)"),
        "git checkout . discards uncommitted changes",
    ),
    (
        "restore-worktree",
        re.compile(r"git\s+restore\s+(?![^\n|;&]*--staged)[^\n|;&]*(\s|^)\.(\s|$|;|\|)"),
        "git restore . discards uncommitted changes",
    ),
    (
        "branch-force-delete",
        re.compile(r"git\s+branch\s+[^\n|;&]*-D\b"),
        "git branch -D discards unmerged work",
    ),
    (
        "stash-drop",
        re.compile(r"git\s+stash\s+(drop|clear)\b"),
        "dropping stashes discards work",
    ),
]

APPROVAL_PREFIX = re.compile(r"^\s*CGEL_GIT=allow\s")

# Every push is outward-facing: on a company remote there is no unpush.
# Gated behind the user's recorded question approval (config: push_gate off).
PUSH_RE = re.compile(r"\bgit\s+push\b")

# Commits and PRs are authored solely by the configured git user.name /
# user.email — never co-authored by, or advertised as generated by, an AI.
# Both halves must match: a command that only *reads* attribution
# (`git log --grep=...`, `grep -r`) is not authoring one and stays allowed.
AUTHORING = re.compile(r"\b(?:git\s+commit|gh\s+pr\s+(?:create|edit))\b")

ATTRIBUTION_RULES = [
    (
        "co-author-trailer",
        re.compile(r"co-authored-by:[^\n]*(?:claude|anthropic)", re.IGNORECASE),
        "a `Co-Authored-By: Claude` trailer",
    ),
    (
        "generated-with-footer",
        re.compile(r"generated\s+with\s+\[?\s*(?:claude|anthropic)", re.IGNORECASE),
        'a "Generated with Claude Code" footer',
    ),
    (
        "robot-footer",
        re.compile(r"\U0001f916\s*generated\s+with", re.IGNORECASE),
        'a "🤖 Generated with ..." footer',
    ),
]


def main():
    try:
        payload = json.load(sys.stdin)
    except Exception as exc:
        C._debug("command_guard:stdin", exc)
        print(
            "CGEL guard: unreadable hook payload — blocking as a precaution "
            "(safety gates fail closed).",
            file=sys.stderr,
        )
        return 2

    if payload.get("tool_name") != "Bash":
        return 0
    if os.environ.get("CGEL_GIT_GUARD", "").lower() == "off":
        return 0

    command = (payload.get("tool_input") or {}).get("command") or ""

    cwd = payload.get("cwd") or os.getcwd()
    repo_root = C.find_repo_root(cwd)
    if not repo_root:
        return 0  # not a CGEL-enabled project
    if C.read_config(repo_root).get("git_guard") == "off":
        return 0

    if APPROVAL_PREFIX.match(command):
        return 0  # explicit per-command approval typed by the user

    for rule_id, pattern, reason in RULES:
        if pattern.search(command):
            flat = approvals.collapse_ws(command)
            found = approvals.find_approval(
                payload.get("transcript_path"), [flat], repo_root
            )
            if found:
                key, _ = found
                approvals.consume(repo_root, key, "git:%s" % rule_id, [flat], command)
                print(
                    approvals.allow_json(
                        "CGEL: user approved this %s command via question" % rule_id
                    )
                )
                return 0
            print(
                "CGEL guard [%s]: blocked — %s. If the user wants this, ask "
                "them with the AskUserQuestion tool, quoting the exact "
                "command in backticks, with options starting with 'Approve' "
                "— then rerun it. They can instead rerun it themselves "
                "prefixed with `CGEL_GIT=allow `." % (rule_id, reason),
                file=sys.stderr,
            )
            return 2

    if PUSH_RE.search(command) and C.read_config(repo_root).get("push_gate") != "off":
        flat = approvals.collapse_ws(command)
        found = approvals.find_approval(
            payload.get("transcript_path"), [flat], repo_root
        )
        if found:
            key, _ = found
            approvals.consume(repo_root, key, "git:push", [flat], command)
            print(approvals.allow_json("CGEL: user approved this push via question"))
            return 0
        print(
            "CGEL guard [push]: pushing to a remote needs the user's recorded "
            "approval. Ask with the AskUserQuestion tool first — quote the "
            "exact command in backticks and say plainly what goes out "
            "(commits ahead, diffstat, latest task outcome) — then rerun it. "
            "The user can instead run it themselves, or rerun prefixed with "
            "`CGEL_GIT=allow `. Off switch: .cgel/config.json "
            '{"push_gate": "off"}.',
            file=sys.stderr,
        )
        return 2

    if (
        AUTHORING.search(command)
        and C.read_config(repo_root).get("ai_attribution_guard") != "off"
    ):
        for rule_id, pattern, reason in ATTRIBUTION_RULES:
            if pattern.search(command):
                print(
                    "CGEL guard [ai-attribution/%s]: blocked — the commit/PR "
                    "text carries %s. Commits and PRs are authored solely by "
                    "the user (the configured git user.name / user.email). "
                    "Rewrite the message as just the change description "
                    "(subject + body), with no Claude/Anthropic/AI mention, "
                    "and retry." % (rule_id, reason),
                    file=sys.stderr,
                )
                return 2

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as exc:  # safety gate: fail closed
        C._debug("command_guard:main", exc)
        print("CGEL guard: internal error — blocking as a precaution.", file=sys.stderr)
        sys.exit(2)
