"""Native OOXML serializer: a RenderedDeck becomes a .pptx package.

Everything here is emitted as strings and packed with `zipfile`. There is no
PPTX library involved, which means every schema obligation is ours to meet.
Three of them decide whether PowerPoint opens the file or offers to repair it,
and none of them produce a visible symptom in more permissive viewers:

1. **Child element order.** OOXML types are XSD *sequences*, not choices. A
   `<a:ln>` placed before `<a:solidFill>` inside `<p:spPr>` is a schema
   violation even though both elements are legal there.
2. **Identifier rules.** Every `cNvPr@id` must be unique within its slide and
   non-zero; every `sldId@id` must be at least 256.
3. **Package integrity.** Every part needs a content-type declaration, and every
   `r:id` needs a relationship that resolves.

XML is written by hand rather than through ElementTree because byte-identical
output depends on controlling attribute order and self-closing tags, which
ElementTree does not guarantee across versions.
"""

from __future__ import annotations

import zipfile
from dataclasses import dataclass

from ..scene import Align, Anchor, LineShape, RectShape, RenderedDeck, RenderedSlide, Shape, TextShape
from ..units import CANVAS_H_PT, CANVAS_W_PT, pt_to_emu

XML_DECL = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'

NS_P = "http://schemas.openxmlformats.org/presentationml/2006/main"
NS_A = "http://schemas.openxmlformats.org/drawingml/2006/main"
NS_R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"

#: A fixed instant for every timestamp in the package. Real build times would
#: make two builds of the same deck differ, which would defeat the determinism
#: guarantee for no benefit -- nobody consults a generated deck's created-date.
FROZEN_TIMESTAMP = "2020-01-01T00:00:00Z"

#: DOS epoch. zipfile cannot encode anything earlier.
FROZEN_ZIP_DATE = (1980, 1, 1, 0, 0, 0)


_INF = float("inf")

#: Characters XML 1.0 forbids outright. They cannot be escaped -- `&#x1F;` is
#: itself illegal -- so they are removed rather than encoded. Tab, newline and
#: carriage return are the only control characters the standard permits.
_ILLEGAL_XML_CHARS = {c for c in range(0x00, 0x20)} - {0x09, 0x0A, 0x0D}


def _finite(value: float, what: str) -> float:
    """Reject a value that cannot be written as an integer attribute.

    A NaN or infinity here is always a defect in arithmetic upstream, never bad
    content. Caught at emission it names the value; allowed through it becomes
    either an attribute PowerPoint refuses to parse or a conversion error
    identifying nothing.
    """
    if value != value or value in (_INF, -_INF):
        raise ValueError(
            f"cannot emit non-finite {what} {value!r}; "
            "this is a defect in layout arithmetic, not in the deck's content"
        )
    return value


def hundredths(value: float, what: str) -> int:
    """Emit a value the schema types in hundredths -- font size, line spacing."""
    return int(round(_finite(value, what)))


def emu(value: float) -> int:
    """Convert points to EMU for emission, refusing anything unrepresentable.

    Every number this module writes into an attribute goes through here. EMU
    attributes are integer-typed in the schema, so a non-finite value would
    either produce an attribute PowerPoint refuses to parse or fail deep inside
    conversion with a message naming neither the value nor the shape it came
    from. A NaN or infinity in layout arithmetic is always a bug upstream, and
    this is the last point that can still say so clearly.

    Guarding at the emission boundary rather than inside the conversion helper
    is deliberate: this module is the only thing that writes attributes, so one
    checkpoint here covers every path without constraining arithmetic elsewhere.
    """
    return pt_to_emu(_finite(value, "coordinate"))


def escape(text: str) -> str:
    """Escape text for use in an XML text node or a quoted attribute.

    Control characters are *stripped*, not escaped. XML 1.0 forbids them
    outright, so `&#x1F;` is itself illegal and encoding one produces a document
    no parser will accept. Since deck content routinely arrives pasted from
    elsewhere or generated by a model, a stray control byte is a realistic input
    rather than a theoretical one -- and silently dropping it is the only
    representable outcome.

    The ampersand must be replaced first, or the escapes introduced by the later
    replacements would themselves be escaped.
    """
    if any(ord(c) in _ILLEGAL_XML_CHARS for c in text):
        text = "".join(c for c in text if ord(c) not in _ILLEGAL_XML_CHARS)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _emu_xfrm(x: float, y: float, w: float, h: float, flip_h: bool = False, flip_v: bool = False) -> str:
    flips = ""
    if flip_h:
        flips += ' flipH="1"'
    if flip_v:
        flips += ' flipV="1"'
    return (
        f"<a:xfrm{flips}>"
        f'<a:off x="{emu(x)}" y="{emu(y)}"/>'
        f'<a:ext cx="{emu(w)}" cy="{emu(h)}"/>'
        f"</a:xfrm>"
    )


# --------------------------------------------------------------------------
# Shape emission
# --------------------------------------------------------------------------


def _rect_xml(shape: RectShape, shape_id: int) -> str:
    r = shape.rect
    if shape.fill:
        fill = f'<a:solidFill><a:srgbClr val="{shape.fill}"/></a:solidFill>'
    else:
        fill = "<a:noFill/>"

    if shape.stroke:
        dash = '<a:prstDash val="dash"/>' if shape.stroke.dashed else '<a:prstDash val="solid"/>'
        line = (
            f'<a:ln w="{emu(shape.stroke.width)}">'
            f'<a:solidFill><a:srgbClr val="{shape.stroke.color}"/></a:solidFill>'
            f"{dash}"
            f"</a:ln>"
        )
    else:
        line = "<a:ln><a:noFill/></a:ln>"

    return (
        "<p:sp>"
        "<p:nvSpPr>"
        f'<p:cNvPr id="{shape_id}" name="{escape(shape.name)}"/>'
        "<p:cNvSpPr/>"
        "<p:nvPr/>"
        "</p:nvSpPr>"
        "<p:spPr>"
        f"{_emu_xfrm(r.x, r.y, r.w, r.h)}"
        '<a:prstGeom prst="rect"><a:avLst/></a:prstGeom>'
        f"{fill}{line}"
        "</p:spPr>"
        # A p:sp must carry a txBody even when it holds no text.
        '<p:txBody><a:bodyPr/><a:lstStyle/><a:p/></p:txBody>'
        "</p:sp>"
    )


def _text_xml(shape: TextShape, shape_id: int) -> str:
    r = shape.rect
    size = hundredths(shape.size_pt * 100, "font size")
    spacing = hundredths(shape.line_height * 100000, "line spacing")
    bold = ' b="1"' if shape.bold else ' b="0"'

    paragraphs = []
    for line in shape.lines:
        if line:
            run = (
                f'<a:r><a:rPr lang="en-US" sz="{size}"{bold} dirty="0">'
                f'<a:solidFill><a:srgbClr val="{shape.color}"/></a:solidFill>'
                f'<a:latin typeface="Arial"/><a:cs typeface="Arial"/>'
                f"</a:rPr><a:t>{escape(line)}</a:t></a:r>"
            )
        else:
            # An empty line still needs a run-properties carrier so the blank
            # paragraph keeps the right height.
            run = f'<a:endParaRPr lang="en-US" sz="{size}"{bold}/>'
        paragraphs.append(
            f'<a:p><a:pPr algn="{shape.align.value}">'
            f'<a:lnSpc><a:spcPct val="{spacing}"/></a:lnSpc>'
            f"</a:pPr>{run}</a:p>"
        )

    inset = emu(shape.inset)
    body_pr = (
        f'<a:bodyPr wrap="square" lIns="{inset}" tIns="{inset}" rIns="{inset}" bIns="{inset}" '
        f'anchor="{shape.anchor.value}">'
        # Autofit is disabled deliberately: the layout already decided the line
        # breaks and the box height. Letting PowerPoint rescale text would
        # silently invalidate every measurement the audit verified.
        "<a:noAutofit/>"
        "</a:bodyPr>"
    )

    return (
        "<p:sp>"
        "<p:nvSpPr>"
        f'<p:cNvPr id="{shape_id}" name="{escape(shape.name)}"/>'
        '<p:cNvSpPr txBox="1"/>'
        "<p:nvPr/>"
        "</p:nvSpPr>"
        "<p:spPr>"
        f"{_emu_xfrm(r.x, r.y, r.w, r.h)}"
        '<a:prstGeom prst="rect"><a:avLst/></a:prstGeom>'
        "<a:noFill/>"
        "</p:spPr>"
        f"<p:txBody>{body_pr}<a:lstStyle/>{''.join(paragraphs)}</p:txBody>"
        "</p:sp>"
    )


def _line_xml(shape: LineShape, shape_id: int) -> str:
    x, y = min(shape.x1, shape.x2), min(shape.y1, shape.y2)
    w, h = abs(shape.x2 - shape.x1), abs(shape.y2 - shape.y1)
    dash = '<a:prstDash val="dash"/>' if shape.stroke.dashed else '<a:prstDash val="solid"/>'

    ends = ""
    if shape.arrow_start:
        ends += '<a:headEnd type="triangle" w="med" len="med"/>'
    if shape.arrow_end:
        ends += '<a:tailEnd type="triangle" w="med" len="med"/>'

    return (
        "<p:sp>"
        "<p:nvSpPr>"
        f'<p:cNvPr id="{shape_id}" name="{escape(shape.name)}"/>'
        "<p:cNvSpPr/>"
        "<p:nvPr/>"
        "</p:nvSpPr>"
        "<p:spPr>"
        f"{_emu_xfrm(x, y, w, h, flip_h=shape.x2 < shape.x1, flip_v=shape.y2 < shape.y1)}"
        '<a:prstGeom prst="line"><a:avLst/></a:prstGeom>'
        "<a:noFill/>"
        f'<a:ln w="{emu(shape.stroke.width)}" cap="flat">'
        f'<a:solidFill><a:srgbClr val="{shape.stroke.color}"/></a:solidFill>'
        f"{dash}{ends}"
        "</a:ln>"
        "</p:spPr>"
        '<p:txBody><a:bodyPr/><a:lstStyle/><a:p/></p:txBody>'
        "</p:sp>"
    )


def _shape_xml(shape: Shape, shape_id: int) -> str:
    if isinstance(shape, RectShape):
        return _rect_xml(shape, shape_id)
    if isinstance(shape, TextShape):
        return _text_xml(shape, shape_id)
    if isinstance(shape, LineShape):
        return _line_xml(shape, shape_id)
    raise TypeError(f"cannot serialize {type(shape).__name__}")


# --------------------------------------------------------------------------
# Parts
# --------------------------------------------------------------------------


def _slide_xml(slide: RenderedSlide) -> str:
    # Shape ids start at 2 because id 1 belongs to the spTree's own group shape.
    body = "".join(_shape_xml(shape, i + 2) for i, shape in enumerate(slide.shapes))
    return (
        XML_DECL
        + f'<p:sld xmlns:a="{NS_A}" xmlns:r="{NS_R}" xmlns:p="{NS_P}">'
        "<p:cSld>"
        f'<p:bg><p:bgPr><a:solidFill><a:srgbClr val="{slide.background}"/></a:solidFill>'
        "<a:effectLst/></p:bgPr></p:bg>"
        "<p:spTree>"
        '<p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>'
        "<p:grpSpPr><a:xfrm>"
        '<a:off x="0" y="0"/><a:ext cx="0" cy="0"/>'
        '<a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/>'
        "</a:xfrm></p:grpSpPr>"
        f"{body}"
        "</p:spTree>"
        "</p:cSld>"
        '<p:clrMapOvr><a:overrideClrMapping bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" '
        'accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" '
        'accent5="accent5" accent6="accent6" hlink="hlink" folHlink="folHlink"/></p:clrMapOvr>'
        "</p:sld>"
    )


def _slide_layout_xml() -> str:
    return (
        XML_DECL
        + f'<p:sldLayout xmlns:a="{NS_A}" xmlns:r="{NS_R}" xmlns:p="{NS_P}" type="blank" preserve="1">'
        "<p:cSld name=\"Blank\">"
        "<p:spTree>"
        '<p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>'
        "<p:grpSpPr><a:xfrm>"
        '<a:off x="0" y="0"/><a:ext cx="0" cy="0"/>'
        '<a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/>'
        "</a:xfrm></p:grpSpPr>"
        "</p:spTree>"
        "</p:cSld>"
        "<p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>"
        "</p:sldLayout>"
    )


def _slide_master_xml() -> str:
    return (
        XML_DECL
        + f'<p:sldMaster xmlns:a="{NS_A}" xmlns:r="{NS_R}" xmlns:p="{NS_P}">'
        "<p:cSld>"
        '<p:bg><p:bgPr><a:solidFill><a:srgbClr val="FFFFFF"/></a:solidFill>'
        "<a:effectLst/></p:bgPr></p:bg>"
        "<p:spTree>"
        '<p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>'
        "<p:grpSpPr><a:xfrm>"
        '<a:off x="0" y="0"/><a:ext cx="0" cy="0"/>'
        '<a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/>'
        "</a:xfrm></p:grpSpPr>"
        "</p:spTree>"
        "</p:cSld>"
        '<p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="accent1" '
        'accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" '
        'accent6="accent6" hlink="hlink" folHlink="folHlink"/>'
        '<p:sldLayoutIdLst><p:sldLayoutId id="2147483649" r:id="rId1"/></p:sldLayoutIdLst>'
        "</p:sldMaster>"
    )


def _theme_xml() -> str:
    """A complete, minimal theme.

    PowerPoint will offer to repair a package whose fmtScheme is incomplete, so
    all four style lists are present with the three entries each the schema
    requires -- even though this deck paints every shape with explicit colours
    and never resolves a theme style.
    """
    accents = ["1F5FA8", "4F86C4", "5B6670", "9AA4AE", "123A66", "22303C"]
    accent_xml = "".join(
        f'<a:accent{i + 1}><a:srgbClr val="{c}"/></a:accent{i + 1}>' for i, c in enumerate(accents)
    )
    fill_style = (
        '<a:fillStyleLst>'
        '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>'
        '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>'
        '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>'
        "</a:fillStyleLst>"
    )
    line_style = (
        "<a:lnStyleLst>"
        + (
            '<a:ln w="6350" cap="flat" cmpd="sng" algn="ctr">'
            '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>'
            '<a:prstDash val="solid"/></a:ln>'
        )
        * 3
        + "</a:lnStyleLst>"
    )
    effect_style = "<a:effectStyleLst>" + "<a:effectStyle><a:effectLst/></a:effectStyle>" * 3 + "</a:effectStyleLst>"
    bg_style = (
        "<a:bgFillStyleLst>"
        + '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>' * 3
        + "</a:bgFillStyleLst>"
    )

    return (
        XML_DECL
        + f'<a:theme xmlns:a="{NS_A}" name="Deck Master">'
        "<a:themeElements>"
        '<a:clrScheme name="Deck Master">'
        '<a:dk1><a:srgbClr val="22303C"/></a:dk1>'
        '<a:lt1><a:srgbClr val="FBFCFD"/></a:lt1>'
        '<a:dk2><a:srgbClr val="1B2732"/></a:dk2>'
        '<a:lt2><a:srgbClr val="EEF2F6"/></a:lt2>'
        f"{accent_xml}"
        '<a:hlink><a:srgbClr val="1F5FA8"/></a:hlink>'
        '<a:folHlink><a:srgbClr val="123A66"/></a:folHlink>'
        "</a:clrScheme>"
        '<a:fontScheme name="Deck Master">'
        '<a:majorFont><a:latin typeface="Arial"/><a:ea typeface=""/><a:cs typeface=""/></a:majorFont>'
        '<a:minorFont><a:latin typeface="Arial"/><a:ea typeface=""/><a:cs typeface=""/></a:minorFont>'
        "</a:fontScheme>"
        '<a:fmtScheme name="Deck Master">'
        f"{fill_style}{line_style}{effect_style}{bg_style}"
        "</a:fmtScheme>"
        "</a:themeElements>"
        "<a:objectDefaults/>"
        "<a:extraClrSchemeLst/>"
        "</a:theme>"
    )


def _presentation_xml(slide_count: int) -> str:
    # sldId values must be >= 256; PowerPoint rejects anything lower.
    slide_ids = "".join(
        f'<p:sldId id="{256 + i}" r:id="rId{i + 2}"/>' for i in range(slide_count)
    )
    return (
        XML_DECL
        + f'<p:presentation xmlns:a="{NS_A}" xmlns:r="{NS_R}" xmlns:p="{NS_P}" saveSubsetFonts="1">'
        '<p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst>'
        f"<p:sldIdLst>{slide_ids}</p:sldIdLst>"
        f'<p:sldSz cx="{emu(CANVAS_W_PT)}" cy="{emu(CANVAS_H_PT)}"/>'
        f'<p:notesSz cx="{emu(CANVAS_H_PT)}" cy="{emu(CANVAS_W_PT)}"/>'
        "</p:presentation>"
    )


def _content_types_xml(slide_count: int) -> str:
    overrides = "".join(
        f'<Override PartName="/ppt/slides/slide{i + 1}.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>'
        for i in range(slide_count)
    )
    return (
        XML_DECL
        + '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/ppt/presentation.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>'
        '<Override PartName="/ppt/slideMasters/slideMaster1.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/>'
        '<Override PartName="/ppt/slideLayouts/slideLayout1.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/>'
        '<Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>'
        f"{overrides}"
        '<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>'
        '<Override PartName="/docProps/app.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>'
        "</Types>"
    )


def _root_rels_xml() -> str:
    return (
        XML_DECL
        + '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" '
        'Target="ppt/presentation.xml"/>'
        '<Relationship Id="rId2" '
        'Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" '
        'Target="docProps/core.xml"/>'
        '<Relationship Id="rId3" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" '
        'Target="docProps/app.xml"/>'
        "</Relationships>"
    )


def _presentation_rels_xml(slide_count: int) -> str:
    base = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
    rels = [f'<Relationship Id="rId1" Type="{base}/slideMaster" Target="slideMasters/slideMaster1.xml"/>']
    for i in range(slide_count):
        rels.append(
            f'<Relationship Id="rId{i + 2}" Type="{base}/slide" Target="slides/slide{i + 1}.xml"/>'
        )
    rels.append(
        f'<Relationship Id="rId{slide_count + 2}" Type="{base}/theme" Target="theme/theme1.xml"/>'
    )
    return (
        XML_DECL
        + '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        + "".join(rels)
        + "</Relationships>"
    )


def _simple_rels_xml(entries: list[tuple[str, str, str]]) -> str:
    base = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
    rels = "".join(
        f'<Relationship Id="{rid}" Type="{base}/{kind}" Target="{target}"/>' for rid, kind, target in entries
    )
    return (
        XML_DECL
        + '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        + rels
        + "</Relationships>"
    )


def _core_xml(deck: RenderedDeck) -> str:
    return (
        XML_DECL
        + '<cp:coreProperties '
        'xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" '
        'xmlns:dc="http://purl.org/dc/elements/1.1/" '
        'xmlns:dcterms="http://purl.org/dc/terms/" '
        'xmlns:dcmitype="http://purl.org/dc/dcmitype/" '
        'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
        f"<dc:title>{escape(deck.title)}</dc:title>"
        f"<dc:creator>{escape(deck.author)}</dc:creator>"
        f"<cp:lastModifiedBy>{escape(deck.author)}</cp:lastModifiedBy>"
        f'<dcterms:created xsi:type="dcterms:W3CDTF">{FROZEN_TIMESTAMP}</dcterms:created>'
        f'<dcterms:modified xsi:type="dcterms:W3CDTF">{FROZEN_TIMESTAMP}</dcterms:modified>'
        "</cp:coreProperties>"
    )


def _app_xml(deck: RenderedDeck) -> str:
    return (
        XML_DECL
        + '<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" '
        'xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">'
        "<Application>Deck Master</Application>"
        f"<Slides>{len(deck.slides)}</Slides>"
        "<ScaleCrop>false</ScaleCrop>"
        "<LinksUpToDate>false</LinksUpToDate>"
        "<SharedDoc>false</SharedDoc>"
        "<HyperlinksChanged>false</HyperlinksChanged>"
        "<AppVersion>16.0000</AppVersion>"
        "</Properties>"
    )


# --------------------------------------------------------------------------
# Package assembly
# --------------------------------------------------------------------------


def build_parts(deck: RenderedDeck) -> list[tuple[str, str]]:
    """Every part in the package, in a fixed order.

    Order is fixed rather than derived from a dict so that the ZIP's central
    directory is identical on every build and on every platform.
    """
    n = len(deck.slides)
    parts: list[tuple[str, str]] = [
        ("[Content_Types].xml", _content_types_xml(n)),
        ("_rels/.rels", _root_rels_xml()),
        ("docProps/app.xml", _app_xml(deck)),
        ("docProps/core.xml", _core_xml(deck)),
        ("ppt/presentation.xml", _presentation_xml(n)),
        ("ppt/_rels/presentation.xml.rels", _presentation_rels_xml(n)),
        ("ppt/slideMasters/slideMaster1.xml", _slide_master_xml()),
        (
            "ppt/slideMasters/_rels/slideMaster1.xml.rels",
            _simple_rels_xml(
                [
                    ("rId1", "slideLayout", "../slideLayouts/slideLayout1.xml"),
                    ("rId2", "theme", "../theme/theme1.xml"),
                ]
            ),
        ),
        ("ppt/slideLayouts/slideLayout1.xml", _slide_layout_xml()),
        (
            "ppt/slideLayouts/_rels/slideLayout1.xml.rels",
            _simple_rels_xml([("rId1", "slideMaster", "../slideMasters/slideMaster1.xml")]),
        ),
        ("ppt/theme/theme1.xml", _theme_xml()),
    ]
    for i, slide in enumerate(deck.slides):
        parts.append((f"ppt/slides/slide{i + 1}.xml", _slide_xml(slide)))
        parts.append(
            (
                f"ppt/slides/_rels/slide{i + 1}.xml.rels",
                _simple_rels_xml([("rId1", "slideLayout", "../slideLayouts/slideLayout1.xml")]),
            )
        )
    return parts


def write_pptx(deck: RenderedDeck, path) -> None:
    """Write the deck to `path` as a .pptx package.

    Determinism is pinned on four axes: fixed part order, a frozen ZIP
    timestamp, `create_system = 0`, and stored rather than deflated entries.

    The first three are the obvious ones. Without the `create_system` pin,
    `zipfile` records the host OS in each entry, so the same deck built on Linux
    and macOS differs byte-for-byte while a build-twice test passes on both.

    The fourth is the subtle one. DEFLATE output is not specified byte-for-byte:
    zlib, zlib-ng and vendor-tuned builds all emit different compressed streams
    for identical input at the same level. Compressing would therefore make the
    file depend on which zlib CPython happens to be linked against -- a host
    dependency that no same-machine test could ever reveal. Storing the parts
    uncompressed removes the compressor from the output entirely. A deck of
    shapes and text is tens of kilobytes either way, so the cost is nothing next
    to a guarantee that actually holds.
    """
    parts = build_parts(deck)
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_STORED) as archive:
        for name, content in parts:
            info = zipfile.ZipInfo(name, date_time=FROZEN_ZIP_DATE)
            info.compress_type = zipfile.ZIP_STORED
            info.create_system = 0  # 0 = MS-DOS, constant across platforms
            info.external_attr = 0o600 << 16
            archive.writestr(info, content.encode("utf-8"))
